import argparse
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset',default='amazon_small')
    parser.add_argument('--train_epoch',type=int,default=30)
    parser.add_argument('--batch_size',type=int,default=1024)
    parser.add_argument('--regs',type=float,default=0.1)
    parser.add_argument('--model',default='model1')
    parser.add_argument('--global_lr',type=float,default=0.0001)
    parser.add_argument('--local_lr', type=float, default=0.005)
    parser.add_argument('--gpu_id',default=0)
    parser.add_argument('--number',default=0)
    parser.add_argument('--mod',default='train')
    parser.add_argument('--test_epoch',type=int,default=10)
    parser.add_argument('--topK',type=int,default=10)
    parser.add_argument('--num_negative_support',type=int,default=3)
    parser.add_argument('--num_negative_evaluation',type=int,default=500)
    parser.add_argument('--exp',default=False)
    parser.add_argument('--random',default='False')
    parser.add_argument('--local_epoch',type=int,default=3)
    return parser.parse_args()
